### ISSUE TITLE
Authorize this app by visiting the external URL and paste in the auth token

### ISSUE THREAD

**Issue by ma7555** [GustavoASC/google-drive-vscode#11]
**Describe the bug**
Can't login to Drive, no where to paste the auth token

**To Reproduce**
Following the installation instructions and providing credentials.json, I was redirected to a page to give access to the App and then an auth token that I should paste into app, another pop up in the app says so too

**Screenshots**
![image](https://user-images.githubusercontent.com/7144929/98837424-9bcd4400-244b-11eb-9074-87c6bd9d74ec.png)

**Please complete the following information:**
 - OS: Win 10 64bit
 - VSCode Version [e.g. 1.51]
 - Extension version [e.g. 1.1.0]

**Additional context**

**Comment by GustavoASC** [comment]
Hello @ma7555, how are you?

When this message appears, an input text also appears (or at least should appear) at the top of VSCode.
Here is the proper place to paste the auth token.

![image](https://user-images.githubusercontent.com/10179520/98963897-ee0f7300-24e6-11eb-8d20-6297f990ada2.png)

Does this input text appear to you?

**Comment by ma7555** [comment]
yes, must have missed it
