### ISSUE TITLE
May you kindly publish your extension to open-vsx.org, https://github.com/open-vsx/publish-extensions

### ISSUE THREAD

**Issue by 304442** [GustavoASC/google-drive-vscode#14]
## Suggestion
May you kindly publish your extension to open-vsx.org, https://github.com/open-vsx/publish-extensions

**Comment by GustavoASC** [comment]
Hello!

Thanks for opening this issue.

I have just published it to Open VSX.
I believe it will be available at 03:03 UTC according to their README.MD file.

Happy coding! :smile:
