### ISSUE TITLE
Share uploaded file to public

### ISSUE THREAD

**Issue by aprakoso98** [GustavoASC/google-drive-vscode#15]
## Overview
I'm an Android developer and sometime need to upload my apk to google drive, but it's time consuming to open google drive and share it manually. Before i use windows and install ShareX
just right click -> upload. The file will uploaded and when it finished it will copy the link to the clipboard. But in mac i didn't found app like thta

## Suggestion
It's be better if in future those feature will be added

**Comment by GustavoASC** [comment]
Hello @aprakoso98 

Thanks for opening this issue!
It is a very nice suggestion :smile:

**Comment by GustavoASC** [comment]
Hello @aprakoso98,

I have developed a command on 1.2.0 to copy file or folder URL to clipboard, through Drive view.
Although this is not exactly what you asked for, with this command we can easily paste the URL on web browser and share file to public through Google Drive itself.

![copy-url](https://user-images.githubusercontent.com/10179520/109397205-62461900-7914-11eb-923f-7bbe47861037.gif)

It was easier to develop it this way and I have been missing the feature to copy URL to clipboard, for other reasons.
Hope it helps! :smile: 

Again, thanks for opening this issue and thanks for using the extension.
Feel free to open new issues as you need.

Regards,
Gustavo Cassel

**Comment by aprakoso98** [comment]
Hi @GustavoASC, I love using this extension.
And thanks for developing my feature request this is much enaugh for me 🙏

**Comment by GustavoASC** [comment]
Hi @aprakoso98 

In case you still use the extension, could you rate it on Marketplace please? :smile: 
Thank you very much!

**Comment by aprakoso98** [comment]
Hi @GustavoASC,

I'm installed Code - Insider, and got error like this

<img width="479" alt="Screen Shot 2021-04-19 at 10 26 29" src="https://user-images.githubusercontent.com/18139422/115177881-513aac80-a0fa-11eb-9d0c-ddff298b6c18.png">

**Comment by GustavoASC** [comment]
Hi @aprakoso98 

Thanks for your comment :smile: 

This problem usually happens when one configures an incorrect credentials.json file, as explained on issue number #7. 
The credentials is probably not configured as a Desktop app.

On the issue mentioned above, a proper warning notification will be shown.
Unfortunately I haven't had the time to add a check yet...
