### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by GustavoASC** [GustavoASC/google-drive-vscode#20]
## Overview
Google has updated the content of [this link ](https://developers.google.com/drive/api/v3/quickstart/nodejs) that is referred by this extension on the README.

Nowadays, there is no button called _Enable the Drive API_.

## Suggestion
Update the README with new steps to configure credentials.

**Comment by xixi-baba** [comment]
will you please update new version of credentials configure??
I did not find the correspoding content mentioned in 'requirements' in the drive API website.

**Comment by GustavoASC** [comment]
Hi @xixi-baba 
Thanks for leaving this comment.
On this exact moment I do not have my computer with me, but I will update the readme as soon as I get my computer again.

For now, I believe you can follow the steps that appear in this link below, where it indicates the step by step to create credentials through the Google Console. You need to provide access to Google Drive API.

https://developers.google.com/workspace/guides/create-credentials

 The most important detail is to configure the credential as Desktop App in your Google Console, as the authentication form that the extension uses is from a Desktop app. Through the Google Console, once you've enabled the Google Drive API, you'll download a .json file that represents your credentials.

With this file in hand, access the Google Drive command: Configure credentials by Visual Studio Code Command Palette and select your .json file.

Hope this helps!

**Comment by GustavoASC** [comment]
Hi @xixi-baba,

Now the README is updated with new requirements.
In case you have any problem following the instructions, feel free to ask again for help.

Thanks in advance!
