### ISSUE TITLE
OAuth out-of-band (oob) is deprecated and does not work anymore

### ISSUE THREAD

**Issue by GustavoASC** [GustavoASC/google-drive-vscode#29]
**Describe the bug**
According to [Google Developer's blog](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#instructions-oob), OAuth out-of-band (oob) is getting deprecated:

> Feb 28, 2022 - new OAuth usage will be blocked for the OOB flow

**To Reproduce**
1. Download credentials.json from Google Console
2. Configure credentials on this extension
3. After selecting the scope, instead of showing a token to copy / paste on the application, an error screen is shown

**Expected behavior**
The auth show complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/10179520/159126552-81a4e24c-66d5-461a-9bcf-6f85528ca760.png)

**Please complete the following information:**
 - OS: Ubuntu 20.04
 - VSCode Version: 1.65.2
 - Extension version 1.3.2

**Comment by gustavosimon** [comment]
Congrats @GustavoASC! Very good!! :D

**Comment by GustavoASC** [comment]
Thank you @gustavosimon! Glad you liked it :smile:
