### ISSUE TITLE
can't find files

### ISSUE THREAD

**Issue by stevenhurwitt** [GustavoASC/google-drive-vscode#3]
hey,

this extension looks really nice, thanks for putting the work into it! unfortunately it doesn't find any of my files when i set up credentials. ideally i would like to see both my drive files and shared drives (if possible on the extension). i can view all of this in python using the same credentials using ```googleapiclient```. 

i'm about to look around in the source for this extension when i have time, but just wondering if this is a common issue?

thanks,
steven

**Comment by stevenhurwitt** [comment]
ahh ok thanks for this! the picker api looks nice. so to quickly meet my needs could i basically edit the scopes in the source and make my own .vsix of that?

**Comment by GustavoASC** [comment]
Yeah, changing the scope on src/auth/driveAuthenticator.ts would allow you to access all of your files.

**Comment by stevenhurwitt** [comment]
thanks for this! as for adding files from shared drives, which part of the source should i edit to add that functionality?

**Comment by GustavoASC** [comment]
You're welcome! :smile:
I have never tested with shared drives... unfortunately I wouldn't know the answer right now... but according to [documentation](https://developers.google.com/drive/api/v3/reference/drives#methods) there are HTTP requests to handle shared drives.

On this extension we use a Node.JS library provided by Google, which simply wraps those HTTP requests into JavaScript functions to make them easier to use. I believe we would need to implement that on src/drive/model/googleDriveFileProvider.ts since this class has access to the Node.JS library.

**Comment by stevenhurwitt** [comment]
ok cool that's helpful, i'll take a look. what i've tried in python is just listing the drives and passing the id to get the files in it - so i'm thinking the google node api must be similar. here's my python prototype:

```python
response = service.drives().list(fields='nextPageToken, drives(id, name)').execute()
shared_drives = [d for d in response.get('drives', [])]

for s in shared_drives:
    result = service.files().list(pageSize=10, 
                                  driveId = s['id'],
                                  corpora = 'drive',
                                  fields="nextPageToken, files(id, name)",
                                  includeItemsFromAllDrives = True,
                                  supportsAllDrives = True).execute()
    
    items = result.get('files', [])
    print('Drive:')
    print(s)
    print('Files:')
    for item in items:
        print(u'{0} ({1})'.format(item['name'], item['id']))
```

**Comment by GustavoASC** [comment]
Great! The node API must be similar to python because both wraps the HTTP requests.

**Comment by stevenhurwitt** [comment]
i might try to extend the hierarchy similar to the UI where everything that shows so far would be under "My Drive" and then shared drives would be under "Shared drives":

![image](https://user-images.githubusercontent.com/7502272/91186189-569f3e80-e6b4-11ea-97ed-988e783014ac.png)

also if i end up implementing this i may add something to the credentials action to ask user whether they want scope to be "drive" or "drive.files"...

**Comment by GustavoASC** [comment]
Fantastic! :clap: :clap:

**Comment by GustavoASC** [comment]
Hi @stevenhurwitt,

On the last version of the extension (1.3.0) it is possible to select different scopes while granting access to the Google Account. Then, it is possible to manage existing files on Drive as well :smile:

**Comment by stevenhurwitt** [comment]
that's awesome, thanks so much!!
