### ISSUE TITLE
Port 3000 occupied

### ISSUE THREAD

**Issue by babaolanqiu** [GustavoASC/google-drive-vscode#35]
Is there a way to change the default server running port? Because I don't have the permission to either check or kill the program running on port 3000. Thanks.

**Comment by GustavoASC** [comment]
Hi @babaolanqiu,

Thanks for trying to use the extension.

I am sorry, but on the moment the number 3000 is hardcoded. We unfortunately have no setting to change this behavior.

I will leave this issue open so this can be improved, okay? Like creating a setting to change the port number or retrying with a different, random port in case the 3000 is busy.

**Comment by GustavoASC** [comment]
Hi @babaolanqiu, we now have the setting _google.drive.authPort_ on version 1.3.4. This allows to configure a specific port number on which a server will be started on the local machine to proceed with the OAuth2 authorization flow. You can specify a value other than 3000.

Thank you @gustavosimon for developing this feature! 😃
