### ISSUE TITLE
Replace keytar with SecretStorage API

### ISSUE THREAD

**Issue by manug23123** [GustavoASC/google-drive-vscode#45]
I have just installed the Extension but although it says that it is globally enabled underneath the installation button it doesn't respond to any commands like Google Drive: Configure credentials.

And in the runtime tab I get the Information "not activated yet".

Can anyone help with that?

**Comment by Ebnater** [comment]
same here

**Comment by GustavoASC** [comment]
It seems to me, that for some reason the extension stopped working after a recent VSCode update. It was working in previous VSCode versions, though 🤔

**Comment by GustavoASC** [comment]
@manug23123 @Ebnater I installed a fresh VSCode 1.83.1 in another computer with Ubuntu 23.04, and it worked fine. May you please share the OS that you are using?

And maybe if you can uninstall the extension and install again, please, and let me know if this worked for you
Thanks!

**Comment by manug23123** [comment]
So I got the Issue on the latest Version of Windows 11 und i did several fresh Installs of both VsCode and the Plugin itself Bit ist still does't work.

Thanks for your Response

**Comment by GustavoASC** [comment]
If you click on the Google Drive button, does this message alsso appear to you?

<img width="504" alt="image" src="https://github.com/GustavoASC/google-drive-vscode/assets/10179520/b7e9e464-8ecf-4254-bd82-988625a5ec77">

**Comment by manug23123** [comment]
> If you click on the Google Drive button, does this message alsso appear to you?
> 
> <img alt="image" width="504" src="https://user-images.githubusercontent.com/10179520/276399428-b7e9e464-8ecf-4254-bd82-988625a5ec77.png">

Yes

**Comment by Ebnater** [comment]
I've reinstalled the extension multiple times on different Computers, but the issue remains. 

On one system is Windows 10 installed and Windows 11 on the other. 

You mentioned that you used Ubuntu. Maybe the issue is OS related?

Greetings

**Comment by GustavoASC** [comment]
So, I discovered that KeyTar support for vscode extensions has ended in September 😢 
https://github.com/microsoft/vscode-discussions/discussions/662
https://github.com/microsoft/vscode/issues/185677

This extension uses keytar to store & retrieve credentials, but from the first link:
> If you are using Keytar directly in your extension, there are a couple of options for you to consider:
> - (recommended) Use the [SecretStorage API](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) that VS Code provides on the [ExtensionContext](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext). This API is cross-platform and will work on all platforms that VS Code supports. It is also maintained by the VS Code team and will continue to be maintained and has been a part of the VS Code API for years at this point.
> - (not recommended) You can bundle the [keytar](https://github.com/atom/node-keytar) module with your extension. Keep in mind that keytar is a native node module which means that you will need to [publish a platform specific extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions) for each platform you want to support.

So it seems like the extension now needs to use the SecretStorage API.

I'll rename this issue, and this is a requirement for the extension to work again.

**Comment by GustavoASC** [comment]
PRs are appreciated in case someone has knowledge on how to use the SecretStorage API, to make the extension work again

**Comment by GustavoASC** [comment]
@manug23123 @Ebnater can you please try again with the version 1.3.9 I published a few minutes ago? This new version uses the SecretStorage API instead of KeyTar, and should be fine for multiple operating systems. I tested on Ubuntu and MacOS and worked fine.

**Comment by Ebnater** [comment]
The new version worked perfectly. I don’t see any errors anymore.
