### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Sullyvian** [GustavoASC/google-drive-vscode#46]
Hello,
When Trying to configure the extension, I get an error after using the Configure credential command in command palette.
VSCode says " command 'google.drive.configureCredentials' not found ".
I can't (or do not know how to) select the path before executing the command.
Do you happen to know what could be wrong ?
I'm on Linux Ubuntu.

Thanks

**Comment by GustavoASC** [comment]
Hi,

I just discovered that KeyTar support for vscode extensions has ended in September 😢
https://github.com/microsoft/vscode-discussions/discussions/662
https://github.com/microsoft/vscode/issues/185677

But I'm working on a fix right now and hopefully I can release the fix today!
I'll let you know :)

**Comment by GustavoASC** [comment]
@Sullyvian can you please try again with the version 1.3.9 I published a few minutes ago? This new version uses the SecretStorage API instead of KeyTar, and should be fine for multiple operating systems. I tested on Ubuntu and MacOS and worked fine.

**Comment by sully-vian** [comment]
It's all working
thanks a lot for giving support for this long
